<a href="https://colab.research.google.com/github/Seth724/CNN-for-Image-Classification/blob/main/pattern_CNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import os

DRIVE_ROOT = "/content/drive/MyDrive/pattern_cnn_experiments"
os.makedirs(DRIVE_ROOT, exist_ok=True)

In [ ]:
!git clone https://github.com/Seth724/CNN-for-Image-Classification.git

fatal: destination path 'CNN-for-Image-Classification' already exists and is not an empty directory.

In [ ]:
%cd /content

!git clone https://github.com/Seth724/CNN-for-Image-Classification.git
%cd /content/CNN-for-Image-Classification

/content
fatal: destination path 'CNN-for-Image-Classification' already exists and is not an empty directory.
/content/CNN-for-Image-Classification

In [ ]:
!find . -maxdepth 2 -type f | sort | head -100

./CNN-for-Image-Classification/.gitignore
./CNN-for-Image-Classification/README.md
./CNN-for-Image-Classification/requirements.txt
./data/README.txt
./documents/colab_hyperparameter_comparison.md
./documents/MobileNetV2_finetuning_plan.md
./EfficientNetV2-B0/config.py
./EfficientNetV2-B0/data.py
./EfficientNetV2-B0/__init__.py
./EfficientNetV2-B0/model.py
./experiments/evaluate_model_b.py
./experiments/__init__.py
./experiments/train_model_b.py
./.git/config
./.git/description
./.git/FETCH_HEAD
./.git/HEAD
./.gitignore
./.git/index
./.git/ORIG_HEAD
./.git/packed-refs
./MobileNetV2/model.py
./README.md
./requirements.txt
./scripts/prepare_data.py
./scripts/train_model_a.py
./scripts/verify_data.py
./src/data_loader.py
./src/evaluation.py
./src/__init__.py
./src/model_b.py
./src/plots.py
./src/utils.py

In [ ]:
import tensorflow as tf

print("TensorFlow:", tf.__version__)
print("GPU devices:", tf.config.list_physical_devices("GPU"))

TensorFlow: 2.21.0
GPU devices: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]

In [ ]:
!ls -lh data/processed

total 33M
-rw-r--r-- 1 root root  30M Oct 15 08:40 fashion_mnist_70_15_15.npz
-rw-r--r-- 1 root root  878 Oct 15 08:40 metadata.json
-rw-r--r-- 1 root root 2.8M Oct 15 08:40 split_manifest.csv

In [ ]:
!python scripts/verify_data.py

Verification PASSED
Dataset : Fashion-MNIST
Seed    : 42
Train   : (49000, 28, 28)
Val     : (10500, 28, 28)
Test    : (10500, 28, 28)

In [ ]:
%cd /content/CNN-for-Image-Classification
!git pull

/content/CNN-for-Image-Classification
Already up to date.

In [ ]:
!python scripts/prepare_data.py
!python scripts/verify_data.py

Done
Train      : (49000, 28, 28)
Validation : (10500, 28, 28)
Test       : (10500, 28, 28)
Saved      : /content/CNN-for-Image-Classification/data/processed/fashion_mnist_70_15_15.npz
Verification PASSED
Dataset : Fashion-MNIST
Seed    : 42
Train   : (49000, 28, 28)
Val     : (10500, 28, 28)
Test    : (10500, 28, 28)

In [ ]:
!python scripts/train_model_a.py \
    --epochs 1 \
    --batch-size 128 \
    --optimizer adam \
    --learning-rate 0.001 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/smoke_test"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054814.263493   86175 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
383/383 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.6120 - loss: 1.0292 - val_accuracy: 0.7255 - val_loss: 0.7539
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/smoke_test
Training time: 14.00 seconds
Test accuracy: 0.7298

In [ ]:
!find "/content/drive/MyDrive/pattern_cnn_experiments/smoke_test" -maxdepth 3 -type f | sort

/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/models/model_a.keras

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer adam \
    --learning-rate 0.001 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054840.233216   86648 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.6128 - loss: 1.0252 - val_accuracy: 0.7270 - val_loss: 0.7584
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7526 - loss: 0.6687 - val_accuracy: 0.7586 - val_loss: 0.6483
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7766 - loss: 0.6032 - val_accuracy: 0.7797 - val_loss: 0.5997
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8010 - loss: 0.5448 - val_accuracy: 0.8073 - val_loss: 0.5297
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8166 - loss: 0.5071 - val_accuracy: 0.8192 - val_loss: 0.5080
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8316 - loss: 0.4693 - val_accuracy: 0.8369 - val_loss: 0.4598
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8398 - loss: 0.4485 - val_accuracy: 0.8457 - val_loss: 0.4400
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8514 - loss: 0.4165 - val_accuracy: 0.8546 - val_loss: 0.4095
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8574 - loss: 0.4011 - val_accuracy: 0.8569 - val_loss: 0.4053
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8637 - loss: 0.3816 - val_accuracy: 0.8559 - val_loss: 0.4060
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8685 - loss: 0.3679 - val_accuracy: 0.8409 - val_loss: 0.4386
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8752 - loss: 0.3508 - val_accuracy: 0.8716 - val_loss: 0.3693
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8765 - loss: 0.3460 - val_accuracy: 0.8763 - val_loss: 0.3438
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8841 - loss: 0.3248 - val_accuracy: 0.8788 - val_loss: 0.3349
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8846 - loss: 0.3186 - val_accuracy: 0.8801 - val_loss: 0.3405
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8895 - loss: 0.3073 - val_accuracy: 0.8748 - val_loss: 0.3494
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8934 - loss: 0.2999 - val_accuracy: 0.8877 - val_loss: 0.3155
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8952 - loss: 0.2923 - val_accuracy: 0.8833 - val_loss: 0.3287
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8987 - loss: 0.2822 - val_accuracy: 0.8911 - val_loss: 0.3115
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8988 - loss: 0.2794 - val_accuracy: 0.8861 - val_loss: 0.3256
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20
Training time: 56.36 seconds
Test accuracy: 0.8896

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer rmsprop \
    --learning-rate 0.001 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792053710.219444   72953 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 13s 20ms/step - accuracy: 0.5329 - loss: 1.2038 - val_accuracy: 0.6005 - val_loss: 0.9936
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7191 - loss: 0.7513 - val_accuracy: 0.7449 - val_loss: 0.6759
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7616 - loss: 0.6423 - val_accuracy: 0.7866 - val_loss: 0.5807
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7875 - loss: 0.5780 - val_accuracy: 0.8032 - val_loss: 0.5352
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8070 - loss: 0.5289 - val_accuracy: 0.8250 - val_loss: 0.4929
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8236 - loss: 0.4858 - val_accuracy: 0.8370 - val_loss: 0.4523
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8361 - loss: 0.4521 - val_accuracy: 0.8470 - val_loss: 0.4333
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8475 - loss: 0.4233 - val_accuracy: 0.8498 - val_loss: 0.4230
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8569 - loss: 0.3970 - val_accuracy: 0.8632 - val_loss: 0.3829
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8649 - loss: 0.3753 - val_accuracy: 0.8703 - val_loss: 0.3584
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8715 - loss: 0.3580 - val_accuracy: 0.8736 - val_loss: 0.3476
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8760 - loss: 0.3402 - val_accuracy: 0.8618 - val_loss: 0.3790
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8824 - loss: 0.3242 - val_accuracy: 0.8725 - val_loss: 0.3565
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8858 - loss: 0.3146 - val_accuracy: 0.8645 - val_loss: 0.3685
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8885 - loss: 0.3021 - val_accuracy: 0.8821 - val_loss: 0.3206
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8938 - loss: 0.2923 - val_accuracy: 0.8848 - val_loss: 0.3212
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8974 - loss: 0.2858 - val_accuracy: 0.8867 - val_loss: 0.3134
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8993 - loss: 0.2756 - val_accuracy: 0.8802 - val_loss: 0.3177
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9027 - loss: 0.2685 - val_accuracy: 0.8840 - val_loss: 0.3234
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9044 - loss: 0.2620 - val_accuracy: 0.8880 - val_loss: 0.3086
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20
Training time: 55.22 seconds
Test accuracy: 0.8971

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer sgd \
    --learning-rate 0.01 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792053777.613279   73826 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 13s 21ms/step - accuracy: 0.1512 - loss: 2.2984 - val_accuracy: 0.1774 - val_loss: 2.2926
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.2079 - loss: 2.2812 - val_accuracy: 0.2270 - val_loss: 2.2625
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.2347 - loss: 2.2207 - val_accuracy: 0.2049 - val_loss: 2.1549
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.2956 - loss: 2.0056 - val_accuracy: 0.3999 - val_loss: 1.7636
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.4758 - loss: 1.4536 - val_accuracy: 0.5851 - val_loss: 1.1768
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.5595 - loss: 1.1341 - val_accuracy: 0.5743 - val_loss: 1.0508
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.5889 - loss: 1.0501 - val_accuracy: 0.5679 - val_loss: 1.0689
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6163 - loss: 0.9911 - val_accuracy: 0.6360 - val_loss: 0.9539
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6321 - loss: 0.9512 - val_accuracy: 0.6291 - val_loss: 0.9523
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6478 - loss: 0.9187 - val_accuracy: 0.6595 - val_loss: 0.8646
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6618 - loss: 0.8907 - val_accuracy: 0.6881 - val_loss: 0.8509
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6704 - loss: 0.8688 - val_accuracy: 0.6384 - val_loss: 0.9120
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6826 - loss: 0.8420 - val_accuracy: 0.6711 - val_loss: 0.8892
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6922 - loss: 0.8209 - val_accuracy: 0.6765 - val_loss: 0.8589
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 5ms/step - accuracy: 0.6975 - loss: 0.8003 - val_accuracy: 0.7062 - val_loss: 0.7736
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7042 - loss: 0.7807 - val_accuracy: 0.7191 - val_loss: 0.7470
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7093 - loss: 0.7657 - val_accuracy: 0.6892 - val_loss: 0.7917
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7131 - loss: 0.7567 - val_accuracy: 0.7171 - val_loss: 0.7360
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7212 - loss: 0.7365 - val_accuracy: 0.7384 - val_loss: 0.7100
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7213 - loss: 0.7265 - val_accuracy: 0.7361 - val_loss: 0.7126
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20
Training time: 54.90 seconds
Test accuracy: 0.7415

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer sgd_momentum \
    --learning-rate 0.01 \
    --momentum 0.9 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792053844.511282   74700 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 13s 21ms/step - accuracy: 0.3421 - loss: 1.7569 - val_accuracy: 0.5705 - val_loss: 1.1144
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.6492 - loss: 0.9173 - val_accuracy: 0.6866 - val_loss: 0.8209
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7070 - loss: 0.7555 - val_accuracy: 0.7255 - val_loss: 0.7103
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7381 - loss: 0.6751 - val_accuracy: 0.7475 - val_loss: 0.6674
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7597 - loss: 0.6282 - val_accuracy: 0.7810 - val_loss: 0.5874
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7853 - loss: 0.5732 - val_accuracy: 0.7982 - val_loss: 0.5585
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7957 - loss: 0.5471 - val_accuracy: 0.8109 - val_loss: 0.5172
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8165 - loss: 0.5024 - val_accuracy: 0.8199 - val_loss: 0.4905
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8239 - loss: 0.4800 - val_accuracy: 0.8266 - val_loss: 0.4765
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8313 - loss: 0.4646 - val_accuracy: 0.8349 - val_loss: 0.4515
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8378 - loss: 0.4460 - val_accuracy: 0.8312 - val_loss: 0.4521
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8413 - loss: 0.4359 - val_accuracy: 0.8512 - val_loss: 0.4114
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8479 - loss: 0.4175 - val_accuracy: 0.8453 - val_loss: 0.4264
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8577 - loss: 0.3935 - val_accuracy: 0.8593 - val_loss: 0.3827
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8593 - loss: 0.3870 - val_accuracy: 0.8631 - val_loss: 0.3865
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8621 - loss: 0.3784 - val_accuracy: 0.8570 - val_loss: 0.3999
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8671 - loss: 0.3681 - val_accuracy: 0.8643 - val_loss: 0.3794
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8685 - loss: 0.3620 - val_accuracy: 0.8572 - val_loss: 0.3826
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8723 - loss: 0.3507 - val_accuracy: 0.8686 - val_loss: 0.3655
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8737 - loss: 0.3437 - val_accuracy: 0.8643 - val_loss: 0.3833
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20
Training time: 55.38 seconds
Test accuracy: 0.8706

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer adam \
    --learning-rate 0.0003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792053911.753374   75577 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.5200 - loss: 1.3252 - val_accuracy: 0.7026 - val_loss: 0.8720
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7118 - loss: 0.7904 - val_accuracy: 0.7325 - val_loss: 0.7425
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7283 - loss: 0.7254 - val_accuracy: 0.7387 - val_loss: 0.7105
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7463 - loss: 0.6829 - val_accuracy: 0.7292 - val_loss: 0.7378
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7577 - loss: 0.6535 - val_accuracy: 0.7699 - val_loss: 0.6332
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7699 - loss: 0.6204 - val_accuracy: 0.7784 - val_loss: 0.6203
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7764 - loss: 0.6034 - val_accuracy: 0.7941 - val_loss: 0.5791
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7900 - loss: 0.5734 - val_accuracy: 0.7980 - val_loss: 0.5679
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7965 - loss: 0.5563 - val_accuracy: 0.8013 - val_loss: 0.5492
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8040 - loss: 0.5417 - val_accuracy: 0.8037 - val_loss: 0.5404
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8117 - loss: 0.5221 - val_accuracy: 0.8069 - val_loss: 0.5240
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8162 - loss: 0.5103 - val_accuracy: 0.8183 - val_loss: 0.5173
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8222 - loss: 0.4965 - val_accuracy: 0.8270 - val_loss: 0.4897
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8278 - loss: 0.4828 - val_accuracy: 0.8318 - val_loss: 0.4746
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8309 - loss: 0.4748 - val_accuracy: 0.8266 - val_loss: 0.4825
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8342 - loss: 0.4612 - val_accuracy: 0.8339 - val_loss: 0.4760
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8396 - loss: 0.4533 - val_accuracy: 0.8381 - val_loss: 0.4605
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8413 - loss: 0.4446 - val_accuracy: 0.8293 - val_loss: 0.4755
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8449 - loss: 0.4354 - val_accuracy: 0.8421 - val_loss: 0.4437
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8465 - loss: 0.4281 - val_accuracy: 0.8429 - val_loss: 0.4401
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20
Training time: 56.72 seconds
Test accuracy: 0.8487

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer adam \
    --learning-rate 0.003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792053980.656156   76459 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.6670 - loss: 0.8713 - val_accuracy: 0.7713 - val_loss: 0.6305
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7970 - loss: 0.5602 - val_accuracy: 0.8237 - val_loss: 0.4901
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8303 - loss: 0.4704 - val_accuracy: 0.8369 - val_loss: 0.4538
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8509 - loss: 0.4154 - val_accuracy: 0.8609 - val_loss: 0.3853
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8661 - loss: 0.3715 - val_accuracy: 0.8602 - val_loss: 0.3958
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8790 - loss: 0.3323 - val_accuracy: 0.8730 - val_loss: 0.3554
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8860 - loss: 0.3120 - val_accuracy: 0.8890 - val_loss: 0.3131
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8947 - loss: 0.2896 - val_accuracy: 0.8929 - val_loss: 0.2960
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9003 - loss: 0.2768 - val_accuracy: 0.8892 - val_loss: 0.3148
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9030 - loss: 0.2669 - val_accuracy: 0.8886 - val_loss: 0.3251
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9087 - loss: 0.2481 - val_accuracy: 0.8926 - val_loss: 0.2992
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9123 - loss: 0.2386 - val_accuracy: 0.9028 - val_loss: 0.2715
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9169 - loss: 0.2307 - val_accuracy: 0.9089 - val_loss: 0.2534
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9210 - loss: 0.2167 - val_accuracy: 0.9088 - val_loss: 0.2543
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9211 - loss: 0.2130 - val_accuracy: 0.9049 - val_loss: 0.2586
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9249 - loss: 0.2019 - val_accuracy: 0.9031 - val_loss: 0.2736
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9302 - loss: 0.1930 - val_accuracy: 0.9071 - val_loss: 0.2567
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9329 - loss: 0.1859 - val_accuracy: 0.8988 - val_loss: 0.2954
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9350 - loss: 0.1774 - val_accuracy: 0.9104 - val_loss: 0.2541
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9376 - loss: 0.1683 - val_accuracy: 0.9058 - val_loss: 0.2660
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20
Training time: 56.81 seconds
Test accuracy: 0.9140

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer adam \
    --learning-rate 0.002 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054049.400682   77340 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.6479 - loss: 0.9199 - val_accuracy: 0.7397 - val_loss: 0.7329
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7779 - loss: 0.6010 - val_accuracy: 0.8085 - val_loss: 0.5311
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8122 - loss: 0.5224 - val_accuracy: 0.8213 - val_loss: 0.4967
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8340 - loss: 0.4616 - val_accuracy: 0.8404 - val_loss: 0.4436
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8498 - loss: 0.4228 - val_accuracy: 0.8440 - val_loss: 0.4444
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8608 - loss: 0.3861 - val_accuracy: 0.8690 - val_loss: 0.3685
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8684 - loss: 0.3650 - val_accuracy: 0.8714 - val_loss: 0.3633
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8791 - loss: 0.3351 - val_accuracy: 0.8745 - val_loss: 0.3451
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8838 - loss: 0.3238 - val_accuracy: 0.8772 - val_loss: 0.3384
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8883 - loss: 0.3068 - val_accuracy: 0.8741 - val_loss: 0.3563
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8957 - loss: 0.2911 - val_accuracy: 0.8734 - val_loss: 0.3509
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8994 - loss: 0.2768 - val_accuracy: 0.8967 - val_loss: 0.2892
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9018 - loss: 0.2730 - val_accuracy: 0.8941 - val_loss: 0.2876
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9058 - loss: 0.2579 - val_accuracy: 0.9006 - val_loss: 0.2730
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9069 - loss: 0.2518 - val_accuracy: 0.8949 - val_loss: 0.2909
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9112 - loss: 0.2428 - val_accuracy: 0.8971 - val_loss: 0.2807
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9154 - loss: 0.2320 - val_accuracy: 0.9065 - val_loss: 0.2625
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9171 - loss: 0.2274 - val_accuracy: 0.9045 - val_loss: 0.2684
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9200 - loss: 0.2178 - val_accuracy: 0.8970 - val_loss: 0.2938
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9238 - loss: 0.2134 - val_accuracy: 0.8993 - val_loss: 0.2843
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20
Training time: 56.65 seconds
Test accuracy: 0.9068

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer adam \
    --learning-rate 0.004 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054117.984470   78218 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 14s 21ms/step - accuracy: 0.6831 - loss: 0.8305 - val_accuracy: 0.7982 - val_loss: 0.5772
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8106 - loss: 0.5152 - val_accuracy: 0.8351 - val_loss: 0.4551
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8442 - loss: 0.4266 - val_accuracy: 0.8450 - val_loss: 0.4167
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8630 - loss: 0.3770 - val_accuracy: 0.8670 - val_loss: 0.3722
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8769 - loss: 0.3394 - val_accuracy: 0.8759 - val_loss: 0.3421
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8875 - loss: 0.3081 - val_accuracy: 0.8870 - val_loss: 0.3090
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8934 - loss: 0.2924 - val_accuracy: 0.8862 - val_loss: 0.3120
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9016 - loss: 0.2688 - val_accuracy: 0.8912 - val_loss: 0.2895
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9060 - loss: 0.2608 - val_accuracy: 0.8982 - val_loss: 0.2793
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9123 - loss: 0.2436 - val_accuracy: 0.8842 - val_loss: 0.3214
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9163 - loss: 0.2317 - val_accuracy: 0.8922 - val_loss: 0.2964
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9200 - loss: 0.2210 - val_accuracy: 0.9065 - val_loss: 0.2599
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9218 - loss: 0.2150 - val_accuracy: 0.9096 - val_loss: 0.2570
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9262 - loss: 0.2016 - val_accuracy: 0.9130 - val_loss: 0.2502
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9280 - loss: 0.1960 - val_accuracy: 0.9074 - val_loss: 0.2540
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9315 - loss: 0.1846 - val_accuracy: 0.9103 - val_loss: 0.2577
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9350 - loss: 0.1783 - val_accuracy: 0.9118 - val_loss: 0.2496
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9389 - loss: 0.1686 - val_accuracy: 0.9066 - val_loss: 0.2674
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9397 - loss: 0.1623 - val_accuracy: 0.9005 - val_loss: 0.2965
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9448 - loss: 0.1524 - val_accuracy: 0.9108 - val_loss: 0.2632
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20
Training time: 56.87 seconds
Test accuracy: 0.9188

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer rmsprop \
    --learning-rate 0.003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054186.993428   79100 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 13s 21ms/step - accuracy: 0.6028 - loss: 1.0446 - val_accuracy: 0.7523 - val_loss: 0.6586
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7849 - loss: 0.5797 - val_accuracy: 0.8195 - val_loss: 0.4885
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8327 - loss: 0.4559 - val_accuracy: 0.8447 - val_loss: 0.4281
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8576 - loss: 0.3840 - val_accuracy: 0.8470 - val_loss: 0.4080
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8717 - loss: 0.3411 - val_accuracy: 0.8649 - val_loss: 0.3788
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8840 - loss: 0.3119 - val_accuracy: 0.8850 - val_loss: 0.3122
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8928 - loss: 0.2901 - val_accuracy: 0.8914 - val_loss: 0.3021
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.8993 - loss: 0.2704 - val_accuracy: 0.8960 - val_loss: 0.2803
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9041 - loss: 0.2542 - val_accuracy: 0.9021 - val_loss: 0.2656
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9100 - loss: 0.2399 - val_accuracy: 0.9096 - val_loss: 0.2500
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 3s 6ms/step - accuracy: 0.9140 - loss: 0.2293 - val_accuracy: 0.9055 - val_loss: 0.2470
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9190 - loss: 0.2161 - val_accuracy: 0.9102 - val_loss: 0.2478
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9248 - loss: 0.2038 - val_accuracy: 0.9130 - val_loss: 0.2453
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9264 - loss: 0.1962 - val_accuracy: 0.8984 - val_loss: 0.2739
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9306 - loss: 0.1844 - val_accuracy: 0.9172 - val_loss: 0.2281
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9336 - loss: 0.1762 - val_accuracy: 0.9120 - val_loss: 0.2434
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9384 - loss: 0.1692 - val_accuracy: 0.9131 - val_loss: 0.2463
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9405 - loss: 0.1610 - val_accuracy: 0.8890 - val_loss: 0.3332
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9433 - loss: 0.1535 - val_accuracy: 0.9127 - val_loss: 0.2687
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9458 - loss: 0.1464 - val_accuracy: 0.9088 - val_loss: 0.2816
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20
Training time: 55.99 seconds
Test accuracy: 0.9123

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer rmsprop \
    --learning-rate 0.004 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054255.150393   79981 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 13s 21ms/step - accuracy: 0.6007 - loss: 1.0345 - val_accuracy: 0.7679 - val_loss: 0.6338
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7997 - loss: 0.5448 - val_accuracy: 0.8307 - val_loss: 0.4686
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8463 - loss: 0.4147 - val_accuracy: 0.8353 - val_loss: 0.4444
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8683 - loss: 0.3550 - val_accuracy: 0.8567 - val_loss: 0.3751
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8811 - loss: 0.3193 - val_accuracy: 0.8804 - val_loss: 0.3361
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8913 - loss: 0.2910 - val_accuracy: 0.8868 - val_loss: 0.3180
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9003 - loss: 0.2700 - val_accuracy: 0.8942 - val_loss: 0.2944
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9066 - loss: 0.2540 - val_accuracy: 0.9044 - val_loss: 0.2616
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9106 - loss: 0.2388 - val_accuracy: 0.9079 - val_loss: 0.2594
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9156 - loss: 0.2248 - val_accuracy: 0.9080 - val_loss: 0.2598
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9189 - loss: 0.2155 - val_accuracy: 0.9121 - val_loss: 0.2428
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9238 - loss: 0.2039 - val_accuracy: 0.8973 - val_loss: 0.2846
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9279 - loss: 0.1913 - val_accuracy: 0.9118 - val_loss: 0.2495
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9311 - loss: 0.1836 - val_accuracy: 0.8814 - val_loss: 0.3464
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9355 - loss: 0.1721 - val_accuracy: 0.9067 - val_loss: 0.2658
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9384 - loss: 0.1648 - val_accuracy: 0.9173 - val_loss: 0.2518
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9407 - loss: 0.1578 - val_accuracy: 0.9149 - val_loss: 0.2557
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9445 - loss: 0.1480 - val_accuracy: 0.9040 - val_loss: 0.2964
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9468 - loss: 0.1406 - val_accuracy: 0.9112 - val_loss: 0.2731
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9504 - loss: 0.1343 - val_accuracy: 0.9078 - val_loss: 0.3159
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20
Training time: 55.70 seconds
Test accuracy: 0.9115

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 128 \
    --optimizer rmsprop \
    --learning-rate 0.002 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054322.939265   80862 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 13s 20ms/step - accuracy: 0.5811 - loss: 1.0917 - val_accuracy: 0.7237 - val_loss: 0.7285
Epoch 2/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.7626 - loss: 0.6384 - val_accuracy: 0.7957 - val_loss: 0.5543
Epoch 3/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8076 - loss: 0.5195 - val_accuracy: 0.8282 - val_loss: 0.4696
Epoch 4/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8403 - loss: 0.4389 - val_accuracy: 0.8131 - val_loss: 0.4861
Epoch 5/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8574 - loss: 0.3870 - val_accuracy: 0.8610 - val_loss: 0.3865
Epoch 6/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8708 - loss: 0.3511 - val_accuracy: 0.8777 - val_loss: 0.3394
Epoch 7/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8809 - loss: 0.3252 - val_accuracy: 0.8824 - val_loss: 0.3200
Epoch 8/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8877 - loss: 0.3042 - val_accuracy: 0.8861 - val_loss: 0.3136
Epoch 9/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8948 - loss: 0.2861 - val_accuracy: 0.8916 - val_loss: 0.2954
Epoch 10/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.8991 - loss: 0.2703 - val_accuracy: 0.8974 - val_loss: 0.2822
Epoch 11/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9032 - loss: 0.2605 - val_accuracy: 0.9066 - val_loss: 0.2590
Epoch 12/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9089 - loss: 0.2456 - val_accuracy: 0.8982 - val_loss: 0.2733
Epoch 13/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9123 - loss: 0.2361 - val_accuracy: 0.9081 - val_loss: 0.2597
Epoch 14/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9156 - loss: 0.2270 - val_accuracy: 0.8843 - val_loss: 0.3189
Epoch 15/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9204 - loss: 0.2174 - val_accuracy: 0.9063 - val_loss: 0.2604
Epoch 16/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9236 - loss: 0.2086 - val_accuracy: 0.9082 - val_loss: 0.2491
Epoch 17/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9249 - loss: 0.2025 - val_accuracy: 0.9108 - val_loss: 0.2456
Epoch 18/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9278 - loss: 0.1944 - val_accuracy: 0.9012 - val_loss: 0.2693
Epoch 19/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9309 - loss: 0.1870 - val_accuracy: 0.9034 - val_loss: 0.2676
Epoch 20/20
383/383 ━━━━━━━━━━━━━━━━━━━━ 2s 6ms/step - accuracy: 0.9323 - loss: 0.1810 - val_accuracy: 0.9135 - val_loss: 0.2391
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20
Training time: 55.08 seconds
Test accuracy: 0.9230

In [ ]:
!python scripts/train_model_a.py \
    --epochs 20 \
    --batch-size 64 \
    --optimizer adam \
    --learning-rate 0.003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054389.958336   81735 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - accuracy: 0.7142 - loss: 0.7632 - val_accuracy: 0.7979 - val_loss: 0.5604
Epoch 2/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8269 - loss: 0.4733 - val_accuracy: 0.8287 - val_loss: 0.4686
Epoch 3/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8574 - loss: 0.3893 - val_accuracy: 0.8710 - val_loss: 0.3628
Epoch 4/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8738 - loss: 0.3423 - val_accuracy: 0.8875 - val_loss: 0.3178
Epoch 5/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8883 - loss: 0.3035 - val_accuracy: 0.8856 - val_loss: 0.3065
Epoch 6/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8980 - loss: 0.2793 - val_accuracy: 0.8944 - val_loss: 0.2870
Epoch 7/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9036 - loss: 0.2595 - val_accuracy: 0.9056 - val_loss: 0.2624
Epoch 8/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9115 - loss: 0.2424 - val_accuracy: 0.9040 - val_loss: 0.2716
Epoch 9/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9155 - loss: 0.2292 - val_accuracy: 0.9058 - val_loss: 0.2651
Epoch 10/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9206 - loss: 0.2168 - val_accuracy: 0.9054 - val_loss: 0.2720
Epoch 11/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9264 - loss: 0.1986 - val_accuracy: 0.8911 - val_loss: 0.3097
Epoch 12/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9301 - loss: 0.1905 - val_accuracy: 0.9141 - val_loss: 0.2445
Epoch 13/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9327 - loss: 0.1818 - val_accuracy: 0.9111 - val_loss: 0.2542
Epoch 14/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9373 - loss: 0.1697 - val_accuracy: 0.9092 - val_loss: 0.2552
Epoch 15/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9411 - loss: 0.1580 - val_accuracy: 0.9119 - val_loss: 0.2444
Epoch 16/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9441 - loss: 0.1506 - val_accuracy: 0.9076 - val_loss: 0.2780
Epoch 17/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9470 - loss: 0.1431 - val_accuracy: 0.9108 - val_loss: 0.2641
Epoch 18/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9513 - loss: 0.1312 - val_accuracy: 0.9126 - val_loss: 0.2925
Epoch 19/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9544 - loss: 0.1236 - val_accuracy: 0.9004 - val_loss: 0.3198
Epoch 20/20
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9569 - loss: 0.1151 - val_accuracy: 0.9079 - val_loss: 0.3196
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20
Training time: 75.14 seconds
Test accuracy: 0.9128

In [ ]:
!python scripts/train_model_a.py \
    --epochs 40 \
    --batch-size 64 \
    --optimizer adam \
    --learning-rate 0.003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054477.432824   82695 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 15s 12ms/step - accuracy: 0.7168 - loss: 0.7555 - val_accuracy: 0.8095 - val_loss: 0.5306
Epoch 2/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8316 - loss: 0.4625 - val_accuracy: 0.8370 - val_loss: 0.4459
Epoch 3/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8587 - loss: 0.3864 - val_accuracy: 0.8691 - val_loss: 0.3723
Epoch 4/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8741 - loss: 0.3434 - val_accuracy: 0.8846 - val_loss: 0.3241
Epoch 5/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8887 - loss: 0.3048 - val_accuracy: 0.8918 - val_loss: 0.3060
Epoch 6/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8988 - loss: 0.2780 - val_accuracy: 0.8924 - val_loss: 0.2908
Epoch 7/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9034 - loss: 0.2615 - val_accuracy: 0.9017 - val_loss: 0.2735
Epoch 8/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9108 - loss: 0.2449 - val_accuracy: 0.9074 - val_loss: 0.2559
Epoch 9/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9150 - loss: 0.2307 - val_accuracy: 0.9025 - val_loss: 0.2652
Epoch 10/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9206 - loss: 0.2165 - val_accuracy: 0.9020 - val_loss: 0.2735
Epoch 11/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9252 - loss: 0.2019 - val_accuracy: 0.8875 - val_loss: 0.3075
Epoch 12/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9287 - loss: 0.1939 - val_accuracy: 0.9127 - val_loss: 0.2434
Epoch 13/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9328 - loss: 0.1815 - val_accuracy: 0.9095 - val_loss: 0.2444
Epoch 14/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9365 - loss: 0.1713 - val_accuracy: 0.9012 - val_loss: 0.2829
Epoch 15/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9394 - loss: 0.1612 - val_accuracy: 0.9149 - val_loss: 0.2336
Epoch 16/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9433 - loss: 0.1520 - val_accuracy: 0.9042 - val_loss: 0.2820
Epoch 17/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9483 - loss: 0.1398 - val_accuracy: 0.9058 - val_loss: 0.2862
Epoch 18/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9505 - loss: 0.1335 - val_accuracy: 0.9115 - val_loss: 0.2700
Epoch 19/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9530 - loss: 0.1238 - val_accuracy: 0.9072 - val_loss: 0.3006
Epoch 20/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9569 - loss: 0.1156 - val_accuracy: 0.9118 - val_loss: 0.2726
Epoch 21/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9597 - loss: 0.1075 - val_accuracy: 0.9074 - val_loss: 0.2896
Epoch 22/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9621 - loss: 0.1007 - val_accuracy: 0.9128 - val_loss: 0.2800
Epoch 23/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9654 - loss: 0.0913 - val_accuracy: 0.9110 - val_loss: 0.3156
Epoch 24/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9672 - loss: 0.0885 - val_accuracy: 0.9150 - val_loss: 0.3000
Epoch 25/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9700 - loss: 0.0799 - val_accuracy: 0.9048 - val_loss: 0.3352
Epoch 26/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9705 - loss: 0.0776 - val_accuracy: 0.9127 - val_loss: 0.3340
Epoch 27/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9741 - loss: 0.0707 - val_accuracy: 0.9100 - val_loss: 0.3418
Epoch 28/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9768 - loss: 0.0629 - val_accuracy: 0.9059 - val_loss: 0.4015
Epoch 29/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9767 - loss: 0.0615 - val_accuracy: 0.9094 - val_loss: 0.3667
Epoch 30/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9794 - loss: 0.0561 - val_accuracy: 0.9097 - val_loss: 0.3844
Epoch 31/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9775 - loss: 0.0585 - val_accuracy: 0.9074 - val_loss: 0.4184
Epoch 32/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9818 - loss: 0.0499 - val_accuracy: 0.9053 - val_loss: 0.4376
Epoch 33/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9810 - loss: 0.0495 - val_accuracy: 0.9057 - val_loss: 0.4020
Epoch 34/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9833 - loss: 0.0446 - val_accuracy: 0.9079 - val_loss: 0.4552
Epoch 35/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9826 - loss: 0.0466 - val_accuracy: 0.9030 - val_loss: 0.5276
Epoch 36/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9866 - loss: 0.0381 - val_accuracy: 0.9071 - val_loss: 0.4961
Epoch 37/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9845 - loss: 0.0410 - val_accuracy: 0.9110 - val_loss: 0.4655
Epoch 38/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9854 - loss: 0.0418 - val_accuracy: 0.9075 - val_loss: 0.5097
Epoch 39/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9849 - loss: 0.0447 - val_accuracy: 0.9101 - val_loss: 0.4836
Epoch 40/40
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9859 - loss: 0.0387 - val_accuracy: 0.9046 - val_loss: 0.4882
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40
Training time: 138.33 seconds
Test accuracy: 0.9149

In [ ]:
!python scripts/train_model_a.py \
    --epochs 10 \
    --batch-size 64 \
    --optimizer adam \
    --learning-rate 0.003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054627.911444   84171 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - accuracy: 0.7164 - loss: 0.7546 - val_accuracy: 0.7969 - val_loss: 0.5572
Epoch 2/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8301 - loss: 0.4656 - val_accuracy: 0.8251 - val_loss: 0.4699
Epoch 3/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8584 - loss: 0.3909 - val_accuracy: 0.8679 - val_loss: 0.3647
Epoch 4/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8736 - loss: 0.3443 - val_accuracy: 0.8844 - val_loss: 0.3241
Epoch 5/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8879 - loss: 0.3057 - val_accuracy: 0.8898 - val_loss: 0.3024
Epoch 6/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8986 - loss: 0.2799 - val_accuracy: 0.8943 - val_loss: 0.2841
Epoch 7/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9031 - loss: 0.2629 - val_accuracy: 0.8974 - val_loss: 0.2822
Epoch 8/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9099 - loss: 0.2454 - val_accuracy: 0.9056 - val_loss: 0.2601
Epoch 9/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9141 - loss: 0.2317 - val_accuracy: 0.9043 - val_loss: 0.2648
Epoch 10/10
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9206 - loss: 0.2157 - val_accuracy: 0.8948 - val_loss: 0.2952
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10
Training time: 43.10 seconds
Test accuracy: 0.9041

In [ ]:
!python scripts/train_model_a.py \
    --epochs 30 \
    --batch-size 64 \
    --optimizer adam \
    --learning-rate 0.003 \
    --seed 42 \
    --output-dir "/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30"

WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
W0000 00:00:1792054683.035421   84871 gpu_bfc_allocator.cc:47] Overriding orig_value setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was false.
Model: "model_a"
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ image (InputLayer)              │ (None, 28, 28, 1)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv1_relu (Conv2D)             │ (None, 28, 28, 32)     │           320 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool1 (MaxPooling2D)            │ (None, 14, 14, 32)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv2_relu (Conv2D)             │ (None, 14, 14, 64)     │        18,496 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ pool2 (MaxPooling2D)            │ (None, 7, 7, 64)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv3_relu (Conv2D)             │ (None, 7, 7, 128)      │        73,856 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ global_average_pool             │ (None, 128)            │             0 │
│ (GlobalAveragePooling2D)        │                        │               │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense64_relu (Dense)            │ (None, 64)             │         8,256 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ class_probabilities (Dense)     │ (None, 10)             │           650 │
└─────────────────────────────────┴────────────────────────┴───────────────┘
 Total params: 101,578 (396.79 KB)
 Trainable params: 101,578 (396.79 KB)
 Non-trainable params: 0 (0.00 B)
Epoch 1/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 14s 11ms/step - accuracy: 0.7125 - loss: 0.7664 - val_accuracy: 0.7950 - val_loss: 0.5674
Epoch 2/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8245 - loss: 0.4795 - val_accuracy: 0.8336 - val_loss: 0.4498
Epoch 3/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8567 - loss: 0.3928 - val_accuracy: 0.8657 - val_loss: 0.3717
Epoch 4/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8734 - loss: 0.3433 - val_accuracy: 0.8845 - val_loss: 0.3234
Epoch 5/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8875 - loss: 0.3082 - val_accuracy: 0.8818 - val_loss: 0.3196
Epoch 6/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.8976 - loss: 0.2808 - val_accuracy: 0.8903 - val_loss: 0.2987
Epoch 7/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9034 - loss: 0.2641 - val_accuracy: 0.9008 - val_loss: 0.2726
Epoch 8/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9093 - loss: 0.2458 - val_accuracy: 0.9004 - val_loss: 0.2764
Epoch 9/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9142 - loss: 0.2336 - val_accuracy: 0.9033 - val_loss: 0.2736
Epoch 10/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9180 - loss: 0.2197 - val_accuracy: 0.8988 - val_loss: 0.2890
Epoch 11/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9236 - loss: 0.2044 - val_accuracy: 0.9007 - val_loss: 0.2822
Epoch 12/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9284 - loss: 0.1932 - val_accuracy: 0.9105 - val_loss: 0.2532
Epoch 13/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9301 - loss: 0.1855 - val_accuracy: 0.9087 - val_loss: 0.2602
Epoch 14/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9360 - loss: 0.1724 - val_accuracy: 0.9051 - val_loss: 0.2758
Epoch 15/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9396 - loss: 0.1616 - val_accuracy: 0.9149 - val_loss: 0.2393
Epoch 16/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9431 - loss: 0.1540 - val_accuracy: 0.9070 - val_loss: 0.2729
Epoch 17/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9470 - loss: 0.1429 - val_accuracy: 0.9112 - val_loss: 0.2642
Epoch 18/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9499 - loss: 0.1340 - val_accuracy: 0.9135 - val_loss: 0.2658
Epoch 19/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9518 - loss: 0.1272 - val_accuracy: 0.9154 - val_loss: 0.2685
Epoch 20/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9588 - loss: 0.1138 - val_accuracy: 0.9106 - val_loss: 0.2945
Epoch 21/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9587 - loss: 0.1099 - val_accuracy: 0.9134 - val_loss: 0.3068
Epoch 22/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9631 - loss: 0.0979 - val_accuracy: 0.9128 - val_loss: 0.2961
Epoch 23/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9657 - loss: 0.0925 - val_accuracy: 0.9136 - val_loss: 0.3103
Epoch 24/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9680 - loss: 0.0856 - val_accuracy: 0.9152 - val_loss: 0.2968
Epoch 25/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9706 - loss: 0.0812 - val_accuracy: 0.9067 - val_loss: 0.3237
Epoch 26/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9714 - loss: 0.0751 - val_accuracy: 0.9173 - val_loss: 0.3066
Epoch 27/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9736 - loss: 0.0711 - val_accuracy: 0.9142 - val_loss: 0.3632
Epoch 28/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9752 - loss: 0.0655 - val_accuracy: 0.9109 - val_loss: 0.3686
Epoch 29/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9774 - loss: 0.0592 - val_accuracy: 0.9083 - val_loss: 0.3679
Epoch 30/30
766/766 ━━━━━━━━━━━━━━━━━━━━ 3s 4ms/step - accuracy: 0.9780 - loss: 0.0601 - val_accuracy: 0.9098 - val_loss: 0.4060
Saved model and metrics under: /content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30
Training time: 107.01 seconds
Test accuracy: 0.9187

In [ ]:
!find "/content/drive/MyDrive/pattern_cnn_experiments" -maxdepth 4 -type f | sort

/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs256_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr1e-3_bs64_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr2e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e10/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e30/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-3_bs64_e40/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr3e-4_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_adam_lr4e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr1e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr2e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr3e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_rmsprop_lr4e-3_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_lr1e-2_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/model_a_sgd_momentum_lr1e-2_m09_bs128_e20/models/model_a.keras
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/figures/training_curves.png
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/architecture.json
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/confusion_matrix.npy
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/confusion_matrix.png
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/evaluation.json
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/metrics/history.csv
/content/drive/MyDrive/pattern_cnn_experiments/smoke_test/models/model_a.keras

In [ ]:
import json
from pathlib import Path
import pandas as pd

root = Path("/content/drive/MyDrive/pattern_cnn_experiments")

rows = []

for evaluation_file in root.glob("*/metrics/evaluation.json"):
    with evaluation_file.open() as f:
        metrics = json.load(f)

    rows.append({
        "experiment": evaluation_file.parent.parent.name,
        "test_accuracy": metrics.get("test_accuracy"),
        "macro_precision": metrics.get("macro_precision"),
        "macro_recall": metrics.get("macro_recall"),
        "macro_f1": metrics.get("macro_f1"),
        "weighted_f1": metrics.get("weighted_f1"),
        "test_loss": metrics.get("test_loss"),
        "epochs": metrics.get("epochs"),
        "batch_size": metrics.get("batch_size"),
        "optimizer": metrics.get("optimizer"),
        "learning_rate": metrics.get("learning_rate"),
        "training_seconds": metrics.get("training_seconds"),
    })

comparison = pd.DataFrame(rows)

if not comparison.empty:
    comparison = comparison.sort_values(
        by=["test_accuracy", "macro_f1"],
        ascending=False,
    )

display(comparison)
comparison.to_csv(root / "model_a_comparison.csv", index=False)

,experiment,test_accuracy,macro_precision,macro_recall,macro_f1,weighted_f1,test_loss,epochs,batch_size,optimizer,learning_rate,training_seconds
13,model_a_rmsprop_lr2e-3_bs128_e20,0.922952,0.924148,0.922952,0.922802,0.922802,0.219893,20,128,rmsprop,0.0020,55.079
10,model_a_adam_lr1e-3_bs64_e20,0.921714,0.921636,0.921714,0.921027,0.921027,0.232631,20,64,adam,0.0030,74.867
11,model_a_adam_lr4e-3_bs128_e20,0.918762,0.918452,0.918762,0.917661,0.917661,0.238148,20,128,adam,0.0040,56.872
8,model_a_adam_lr3e-3_bs64_e30,0.918667,0.920329,0.918667,0.918829,0.918829,0.367566,30,64,adam,0.0030,107.012
12,model_a_adam_lr3e-3_bs64_e40,0.914857,0.916059,0.914857,0.915045,0.915045,0.425308,40,64,adam,0.0030,138.326
16,model_a_adam_lr3e-3_bs128_e20,0.914000,0.914881,0.914000,0.912582,0.912582,0.248518,20,128,adam,0.0030,56.809
5,model_a_adam_lr3e-3_bs64_e20,0.912762,0.914105,0.912762,0.912574,0.912574,0.279988,20,64,adam,0.0030,75.138
9,model_a_rmsprop_lr3e-3_bs128_e20,0.912286,0.917539,0.912286,0.910688,0.910688,0.264597,20,128,rmsprop,0.0030,55.990
3,model_a_rmsprop_lr4e-3_bs128_e20,0.911524,0.916218,0.911524,0.911173,0.911173,0.299113,20,128,rmsprop,0.0040,55.699
2,model_a_adam_lr2e-3_bs128_e20,0.906762,0.909711,0.906762,0.904726,0.904726,0.262770,20,128,adam,0.0020,56.653
6,model_a_adam_lr3e-3_bs64_e10,0.904095,0.908363,0.904095,0.903704,0.903704,0.267264,10,64,adam,0.0030,43.101
7,model_a_adam_lr1e-3_bs256_e20,0.903810,0.908561,0.903810,0.901330,0.901330,0.262590,20,256,adam,0.0030,46.413
4,model_a_rmsprop_lr1e-3_bs128_e20,0.897143,0.903039,0.897143,0.896208,0.896208,0.279427,20,128,rmsprop,0.0010,55.218
14,model_a_adam_lr1e-3_bs128_e20,0.889619,0.895407,0.889619,0.884679,0.884679,0.307545,20,128,adam,0.0010,56.358
0,model_a_sgd_momentum_lr1e-2_m09_bs128_e20,0.870571,0.874985,0.870571,0.864877,0.864877,0.359773,20,128,sgd_momentum,0.0100,55.378
17,model_a_adam_lr3e-4_bs128_e20,0.848667,0.853741,0.848667,0.842194,0.842194,0.417057,20,128,adam,0.0003,56.720
1,model_a_sgd_lr1e-2_bs128_e20,0.741524,0.743087,0.741524,0.732969,0.732969,0.699247,20,128,sgd,0.0100,54.904
15,smoke_test,0.729810,0.729644,0.729810,0.715542,0.715542,0.737268,1,128,adam,0.0010,13.999

In [ ]:
display(comparison.head(10))

,experiment,test_accuracy,macro_precision,macro_recall,macro_f1,weighted_f1,test_loss,epochs,batch_size,optimizer,learning_rate,training_seconds
13,model_a_rmsprop_lr2e-3_bs128_e20,0.922952,0.924148,0.922952,0.922802,0.922802,0.219893,20,128,rmsprop,0.002,55.079
10,model_a_adam_lr1e-3_bs64_e20,0.921714,0.921636,0.921714,0.921027,0.921027,0.232631,20,64,adam,0.003,74.867
11,model_a_adam_lr4e-3_bs128_e20,0.918762,0.918452,0.918762,0.917661,0.917661,0.238148,20,128,adam,0.004,56.872
8,model_a_adam_lr3e-3_bs64_e30,0.918667,0.920329,0.918667,0.918829,0.918829,0.367566,30,64,adam,0.003,107.012
12,model_a_adam_lr3e-3_bs64_e40,0.914857,0.916059,0.914857,0.915045,0.915045,0.425308,40,64,adam,0.003,138.326
16,model_a_adam_lr3e-3_bs128_e20,0.914000,0.914881,0.914000,0.912582,0.912582,0.248518,20,128,adam,0.003,56.809
5,model_a_adam_lr3e-3_bs64_e20,0.912762,0.914105,0.912762,0.912574,0.912574,0.279988,20,64,adam,0.003,75.138
9,model_a_rmsprop_lr3e-3_bs128_e20,0.912286,0.917539,0.912286,0.910688,0.910688,0.264597,20,128,rmsprop,0.003,55.990
3,model_a_rmsprop_lr4e-3_bs128_e20,0.911524,0.916218,0.911524,0.911173,0.911173,0.299113,20,128,rmsprop,0.004,55.699
2,model_a_adam_lr2e-3_bs128_e20,0.906762,0.909711,0.906762,0.904726,0.904726,0.262770,20,128,adam,0.002,56.653